version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-blogpageOne
    ports:
      - "27017:27017"
    networks:
      - blog-app-network

networks:
  blog-app-network:
    driver: bridge